---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: sleep
          command: /bin/sleep 15
          async: 1000
          poll: 0
          register: sleep
      become: true

