---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: user1
          user:
            name: "{{ user }}"
            state: present
          register: error
        - name: install curl
          apt:
            name: curl
            update-cache: yes
          register: error
        - name: Fail on failed
          command: echo "FAILED"
          register: command_result
          failed_when: "'FAILED' in command_result.stdout"
      become: true
      rescue:
        - name: Some error print
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: "Reboooooting"