---
- name: user
  hosts: demo
  tasks:
    - name: Create user
      vars:
        user: user1
      user:
        name: "{{ user }}"
        state: present
      become: true
      register: out
    - debug:
        var: out
